import { figma } from "@figma/code-connect";
import React from "react";
import { Button } from "../button/Button.jsx";
import {
    Modal,
    ModalActions,
    ModalBody,
    ModalCloseButton,
    ModalContainer,
    ModalHeader,
    ModalOverlay,
    ModalTitle,
} from "./Modal.js";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Modal,
    "https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv?node-id=2075%3A15258",
    {
        imports: [
            'import { Modal, ModalContainer, ModalOverlay, ModalHeader, ModalTitle, ModalCloseButton, ModalBody, ModalActions } from "@fremtind/jokul/components/modal";',
        ],
        props: {
            children: figma.boolean("Show Text", {
                false: figma.instance("Content"),
                true: figma.string("Text"),
            }),
            title: figma.string("Title"),
        },
        example: (props) => (
            <ModalContainer
                role="document"
                id="my-modal"
                aria-labelledby="heading"
                aria-modal
                aria-hidden={false}
            >
                <ModalOverlay />
                <Modal role="document">
                    <ModalHeader>
                        {/* biome-ignore lint/a11y/useSemanticElements:  */}
                        <ModalTitle aria-level={1} role="heading" id={""}>
                            {props.title}
                        </ModalTitle>
                        <ModalCloseButton type="button" aria-label="close" />
                    </ModalHeader>
                    <ModalBody>{props.children}</ModalBody>
                    <ModalActions>
                        <Button>Avbryt</Button>
                        <Button variant="primary" data-testid="confirm-modal">
                            Slett
                        </Button>
                    </ModalActions>
                </Modal>
            </ModalContainer>
        ),
    },
);
