language: node_js
node_js:
    - "lts/dubnium"
cache:
    directories:
        - "node_modules"
        - "build"
script:
    - yarn
    - yarn setup
    - yarn build:docs
    - yarn lint:ts
    - yarn test:ci
branch: master
