language: node_js
node_js:
    - "--lts"
cache:
    yarn: true
jobs:
    include:
        - stage: "build"
          name: "Build packages"
          script: yarn build
        - stage: "lint"
          name: "Lint"
          script: "yarn lint"
        - stage: "typecheck"
          name: "Check types"
          script: "yarn typecheck"
        - stage: "test"
          name: "Unit Tests"
          script: yarn test:ci
        - stage: "deploy"
          name: "build docs and deploy"
          if: branch = master
          script: yarn build:docs
          deploy:
              provider: pages
              local_dir: "./portal/public"
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              keep_history: true
              on:
                  branch: master

# Only build PRs and master
# https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
branches:
    only:
        - master
