language: node_js
node_js:
    - "--lts"
cache: yarn
    directories:
        - "node_modules"
script:
    - yarn
    - yarn setup
    - yarn build:docs
    - yarn lint:ts
    - yarn test:ci
branch: master
