import { figma } from "@figma/code-connect";
import { BreadcrumbItem } from "./BreadcrumbItem.js";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    BreadcrumbItem,
    "https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv?node-id=2006%3A3137",
    {
        imports: [
            'import { BreadcrumbItem } from "@fremtind/jokul/components/breadcrumb";',
        ],
        props: {
            isLastElement: figma.boolean("Current"),
        },
        example: (props) => <BreadcrumbItem {...props}>Hei</BreadcrumbItem>,
    },
);
