import { figma } from "@figma/code-connect";
import React from "react";
import { TextInput } from "./TextInput.js";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    TextInput,
    "https://www.figma.com/design/jnE6mPCHVfbjn7a0AiKGEK?node-id=30699%3A1281",
    {
        imports: [
            'import { TextInput } from "@fremtind/jokul/components/text-input";',
        ],
        props: {
            value: figma.enum("Has Value", {
                True: figma.string("Value"),
                False: undefined,
            }),
            description: figma.boolean("Show Description", {
                true: figma.string("Description"),
                false: undefined,
            }),
            placeholder: figma.string("Placeholder"),
            label: figma.string("Label"),
        },
        example: ({ ...props }) => <TextInput {...props} />,
    },
);
