import { figma } from "@figma/code-connect";
import { TextInput } from "./TextInput.js";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    TextInput,
    "https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv?node-id=2007%3A2426",
    {
        imports: [
            'import { TextInput } from "@fremtind/jokul/components/text-input";',
        ],
        props: {
            value: figma.boolean("Show Text", {
                true: figma.string("↳ Text"),
                false: undefined,
            }),
            placeholder: figma.string("↳ Placeholder Text"),
            nested: figma.nestedProps("Label", {
                label: figma.string("Text"),
            }),
        },
        example: ({ nested, ...props }) => (
            <TextInput label={nested.label} {...props} />
        ),
    },
);
