name: Forslag
description: Del dine forslag og innspill til Jøkul
title: "Tilbakemelding: "
labels: ["✨ Forslag"]
type: "Feature"
body:
    - type: markdown
      attributes:
          value: |
              Tusen takk for at du bidrar til å forbedre Jøkul!
    - type: textarea
      id: feedback
      attributes:
          label: Innspill
          description: Beskriv hvilke forbedringer eller tilbakemeldinger du har.
