module.exports = {
    // Regler som er skrudd av er outsourcet til Prettier
    "scss/at-else-closing-brace-newline-after": null,
    "scss/at-else-closing-brace-space-after": null,
    "scss/at-else-empty-line-before": null,
    "scss/at-else-if-parentheses-space-before": null,
    "scss/at-function-pattern": "^_?[a-z-]+$",
    "scss/at-function-parentheses-space-before": null,
    "scss/at-if-closing-brace-newline-after": null,
    "scss/at-if-closing-brace-space-after": null,
    "scss/at-import-no-partial-leading-underscore": null,
    "scss/at-mixin-parentheses-space-before": null,
    "scss/at-mixin-pattern": "^_?[a-z-]+$",
    "scss/dollar-variable-colon-newline-after": null,
    "scss/dollar-variable-colon-space-after": null,
    "scss/dollar-variable-colon-space-before": null,
    "scss/dollar-variable-empty-line-after": null,
    "scss/dollar-variable-empty-line-before": null,
    "scss/dollar-variable-pattern": "^_?[a-z\\d-]*$",
    "scss/double-slash-comment-empty-line-before": null,
    "scss/map-keys-quotes": "always",
    "scss/operator-no-newline-after": null,
    "scss/operator-no-newline-before": null,
    "scss/operator-no-unspaced": null,
};
