export const landkoder = [
    { kode: "AF", navn: "Afghanistan" },
    { kode: "AL", navn: "Albania" },
    { kode: "DZ", navn: "Algerie" },
    { kode: "AS", navn: "Amerikansk Samoa" },
    { kode: "AD", navn: "Andorra" },
    { kode: "AO", navn: "Angola" },
    { kode: "AI", navn: "Anguilla" },
    { kode: "AQ", navn: "Antarktis" },
    { kode: "AG", navn: "Antigua og Barbuda" },
    { kode: "AR", navn: "Argentina" },
    { kode: "AM", navn: "Armenia" },
    { kode: "AW", navn: "Aruba" },
    { kode: "AZ", navn: "Aserbajdsjan" },
    { kode: "AU", navn: "Australia" },
    { kode: "BS", navn: "Bahamas" },
    { kode: "BH", navn: "Bahrain" },
    { kode: "BD", navn: "Bangladesh" },
    { kode: "BB", navn: "Barbados" },
    { kode: "BY", navn: "Belarus" },
    { kode: "BE", navn: "Belgia" },
    { kode: "BZ", navn: "Belize" },
    { kode: "BJ", navn: "Benin" },
    { kode: "BM", navn: "Bermuda" },
    { kode: "BT", navn: "Bhutan" },
    { kode: "BO", navn: "Bolivia" },
    { kode: "BQ", navn: "Bonaire, Sint Eustatius og Saba" },
    { kode: "BA", navn: "Bosnia-Hercegovina" },
    { kode: "BW", navn: "Botswana" },
    { kode: "BV", navn: "Bouvetøya" },
    { kode: "BR", navn: "Brasil" },
    { kode: "BN", navn: "Brunei" },
    { kode: "BG", navn: "Bulgaria" },
    { kode: "BF", navn: "Burkina Faso" },
    { kode: "BI", navn: "Burundi" },
    { kode: "CA", navn: "Canada" },
    { kode: "KY", navn: "Caymanøyene" },
    { kode: "XC", navn: "Ceuta og Melilla" },
    { kode: "CL", navn: "Chile" },
    { kode: "CX", navn: "Christmasøya" },
    { kode: "CO", navn: "Colombia" },
    { kode: "CK", navn: "Cookøyene" },
    { kode: "CR", navn: "Costa Rica" },
    { kode: "CU", navn: "Cuba" },
    { kode: "CW", navn: "Curaçao" },
    { kode: "DK", navn: "Danmark" },
    { kode: "VI", navn: "De amerikanske Jomfruøyer" },
    { kode: "VG", navn: "De britiske Jomfruøyer" },
    { kode: "AE", navn: "De forente arabiske emirater" },
    { kode: "TF", navn: "De franske sørterritorier" },
    { kode: "DO", navn: "Den dominikanske republikk" },
    { kode: "CF", navn: "Den sentralafrikanske republikk" },
    { kode: "IO", navn: "Det britiske territorium i Indiahavet" },
    { kode: "DJ", navn: "Djibouti" },
    { kode: "DM", navn: "Dominica" },
    { kode: "EC", navn: "Ecuador" },
    { kode: "EG", navn: "Egypt" },
    { kode: "GQ", navn: "Ekvatorial-Guinea" },
    { kode: "SV", navn: "El Salvador" },
    { kode: "CI", navn: "Elfenbeinskysten" },
    { kode: "ER", navn: "Eritrea" },
    { kode: "EE", navn: "Estland" },
    { kode: "SZ", navn: "Eswatini" },
    { kode: "ET", navn: "Etiopia" },
    { kode: "FK", navn: "Falklandsøyene" },
    { kode: "FJ", navn: "Fiji" },
    { kode: "PH", navn: "Filippinene" },
    { kode: "FI", navn: "Finland" },
    { kode: "FR", navn: "Frankrike" },
    { kode: "GF", navn: "Fransk Guyana" },
    { kode: "PF", navn: "Fransk Polynesia" },
    { kode: "FO", navn: "Færøyene" },
    { kode: "GA", navn: "Gabon" },
    { kode: "GM", navn: "Gambia" },
    { kode: "GE", navn: "Georgia" },
    { kode: "GH", navn: "Ghana" },
    { kode: "GI", navn: "Gibraltar" },
    { kode: "GD", navn: "Grenada" },
    { kode: "GL", navn: "Grønland" },
    { kode: "GP", navn: "Guadeloupe" },
    { kode: "GU", navn: "Guam" },
    { kode: "GT", navn: "Guatemala" },
    { kode: "GG", navn: "Guernsey" },
    { kode: "GN", navn: "Guinea" },
    { kode: "GW", navn: "Guinea-Bissau" },
    { kode: "GY", navn: "Guyana" },
    { kode: "HT", navn: "Haiti" },
    { kode: "HM", navn: "Heard- og McDonaldøyene" },
    { kode: "GR", navn: "Hellas" },
    { kode: "HN", navn: "Honduras" },
    { kode: "HK", navn: "Hongkong" },
    { kode: "IN", navn: "India" },
    { kode: "ID", navn: "Indonesia" },
    { kode: "IQ", navn: "Irak" },
    { kode: "IR", navn: "Iran" },
    { kode: "IE", navn: "Irland" },
    { kode: "IS", navn: "Island" },
    { kode: "IL", navn: "Israel" },
    { kode: "IT", navn: "Italia" },
    { kode: "JM", navn: "Jamaica" },
    { kode: "JP", navn: "Japan" },
    { kode: "YE", navn: "Jemen" },
    { kode: "JE", navn: "Jersey" },
    { kode: "JO", navn: "Jordan" },
    { kode: "KH", navn: "Kambodsja" },
    { kode: "CM", navn: "Kamerun" },
    { kode: "XB", navn: "Kanariøyene" },
    { kode: "CV", navn: "Kapp Verde" },
    { kode: "KZ", navn: "Kasakhstan" },
    { kode: "KE", navn: "Kenya" },
    { kode: "CN", navn: "Kina" },
    { kode: "KG", navn: "Kirgisistan" },
    { kode: "KI", navn: "Kiribati" },
    { kode: "CC", navn: "Kokosøyene" },
    { kode: "KM", navn: "Komorene" },
    { kode: "CD", navn: "Kongo" },
    { kode: "CG", navn: "Kongo - Brazzaville" },
    { kode: "XK", navn: "Kosovo" },
    { kode: "HR", navn: "Kroatia" },
    { kode: "KW", navn: "Kuwait" },
    { kode: "CY", navn: "Kypros" },
    { kode: "LA", navn: "Laos" },
    { kode: "LV", navn: "Latvia" },
    { kode: "LS", navn: "Lesotho" },
    { kode: "LB", navn: "Libanon" },
    { kode: "LR", navn: "Liberia" },
    { kode: "LY", navn: "Libya" },
    { kode: "LI", navn: "Liechtenstein" },
    { kode: "LT", navn: "Litauen" },
    { kode: "LU", navn: "Luxembourg" },
    { kode: "MO", navn: "Macao" },
    { kode: "MG", navn: "Madagaskar" },
    { kode: "MW", navn: "Malawi" },
    { kode: "MY", navn: "Malaysia" },
    { kode: "MV", navn: "Maldivene" },
    { kode: "ML", navn: "Mali" },
    { kode: "MT", navn: "Malta" },
    { kode: "IM", navn: "Man" },
    { kode: "MA", navn: "Marokko" },
    { kode: "MH", navn: "Marshalløyene" },
    { kode: "MQ", navn: "Martinique" },
    { kode: "MR", navn: "Mauritania" },
    { kode: "MU", navn: "Mauritius" },
    { kode: "YT", navn: "Mayotte" },
    { kode: "MX", navn: "Mexico" },
    { kode: "FM", navn: "Mikronesiaføderasjonen" },
    { kode: "MD", navn: "Moldova" },
    { kode: "MC", navn: "Monaco" },
    { kode: "MN", navn: "Mongolia" },
    { kode: "ME", navn: "Montenegro" },
    { kode: "MS", navn: "Montserrat" },
    { kode: "MZ", navn: "Mosambik" },
    { kode: "MM", navn: "Myanmar" },
    { kode: "NA", navn: "Namibia" },
    { kode: "NR", navn: "Nauru" },
    { kode: "NL", navn: "Nederland" },
    { kode: "NP", navn: "Nepal" },
    { kode: "NZ", navn: "New Zealand" },
    { kode: "NI", navn: "Nicaragua" },
    { kode: "NE", navn: "Niger" },
    { kode: "NG", navn: "Nigeria" },
    { kode: "NU", navn: "Niue" },
    { kode: "KP", navn: "Nord-Korea" },
    { kode: "MK", navn: "Nord-Makedonia" },
    { kode: "MP", navn: "Nord-Marianene" },
    { kode: "NF", navn: "Norfolkøya" },
    { kode: "NO", navn: "Norge" },
    { kode: "NC", navn: "Ny-Caledonia" },
    { kode: "OM", navn: "Oman" },
    { kode: "PK", navn: "Pakistan" },
    { kode: "PW", navn: "Palau" },
    { kode: "PS", navn: "Palestina" },
    { kode: "PA", navn: "Panama" },
    { kode: "PG", navn: "Papua Ny-Guinea" },
    { kode: "PY", navn: "Paraguay" },
    { kode: "PE", navn: "Peru" },
    { kode: "PN", navn: "Pitcairn" },
    { kode: "PL", navn: "Polen" },
    { kode: "PT", navn: "Portugal" },
    { kode: "PR", navn: "Puerto Rico" },
    { kode: "QA", navn: "Qatar" },
    { kode: "RE", navn: "Réunion" },
    { kode: "RO", navn: "Romania" },
    { kode: "RU", navn: "Russland" },
    { kode: "RW", navn: "Rwanda" },
    { kode: "BL", navn: "Saint-Barthélemy" },
    { kode: "MF", navn: "Saint-Martin (FR)" },
    { kode: "PM", navn: "Saint-Pierre-et-Miquelon" },
    { kode: "SB", navn: "Salomonøyene" },
    { kode: "WS", navn: "Samoa" },
    { kode: "SM", navn: "San Marino" },
    { kode: "SH", navn: "Sankt Helena, Ascension og Tristan da Cunha" },
    { kode: "ST", navn: "São Tomé og Príncipe" },
    { kode: "SA", navn: "Saudi-Arabia" },
    { kode: "SN", navn: "Senegal" },
    { kode: "RS", navn: "Serbia" },
    { kode: "SC", navn: "Seychellene" },
    { kode: "SL", navn: "Sierra Leone" },
    { kode: "SG", navn: "Singapore" },
    { kode: "SX", navn: "Sint Maarten (NL)" },
    { kode: "SK", navn: "Slovakia" },
    { kode: "SI", navn: "Slovenia" },
    { kode: "SO", navn: "Somalia" },
    { kode: "ES", navn: "Spania" },
    { kode: "LK", navn: "Sri Lanka" },
    { kode: "KN", navn: "St. Kitts og Nevis" },
    { kode: "LC", navn: "St. Lucia" },
    { kode: "VC", navn: "St. Vincent og Grenadinene" },
    { kode: "GB", navn: "Storbritannia" },
    { kode: "SD", navn: "Sudan" },
    { kode: "SR", navn: "Surinam" },
    { kode: "SJ", navn: "Svalbard og Jan Mayen" },
    { kode: "CH", navn: "Sveits" },
    { kode: "SE", navn: "Sverige" },
    { kode: "SY", navn: "Syria" },
    { kode: "ZA", navn: "Sør-Afrika" },
    { kode: "GS", navn: "Sør-Georgia og Sør-Sandwichøyene" },
    { kode: "KR", navn: "Sør-Korea" },
    { kode: "SS", navn: "Sør-Sudan" },
    { kode: "TJ", navn: "Tadsjikistan" },
    { kode: "TW", navn: "Taiwan" },
    { kode: "TZ", navn: "Tanzania" },
    { kode: "TH", navn: "Thailand" },
    { kode: "TG", navn: "Togo" },
    { kode: "TK", navn: "Tokelau" },
    { kode: "TO", navn: "Tonga" },
    { kode: "TT", navn: "Trinidad og Tobago" },
    { kode: "TD", navn: "Tsjad" },
    { kode: "CZ", navn: "Tsjekkia" },
    { kode: "TN", navn: "Tunisia" },
    { kode: "TM", navn: "Turkmenistan" },
    { kode: "TC", navn: "Turks- og Caicosøyene" },
    { kode: "TV", navn: "Tuvalu" },
    { kode: "TR", navn: "Tyrkia" },
    { kode: "DE", navn: "Tyskland" },
    { kode: "UG", navn: "Uganda" },
    { kode: "UA", navn: "Ukraina" },
    { kode: "HU", navn: "Ungarn" },
    { kode: "UY", navn: "Uruguay" },
    { kode: "US", navn: "USA" },
    { kode: "UM", navn: "USAs ytre småøyer" },
    { kode: "UZ", navn: "Usbekistan" },
    { kode: "VU", navn: "Vanuatu" },
    { kode: "VA", navn: "Vatikanstaten" },
    { kode: "VE", navn: "Venezuela" },
    { kode: "EH", navn: "Vest-Sahara" },
    { kode: "VN", navn: "Vietnam" },
    { kode: "WF", navn: "Wallis- og Futunaøyene" },
    { kode: "ZM", navn: "Zambia" },
    { kode: "ZW", navn: "Zimbabwe" },
    { kode: "TL", navn: "Øst-Timor" },
    { kode: "AT", navn: "Østerrike" },
    { kode: "AX", navn: "Åland" },
] as const;
