/**
 * En liste med navn på alle komponentene våre. Dette kan brukes til sporing og logging.
 */
export const COMPONENT_NAMES = {
    Autosuggest: "Autosuggest",
    Breadcrumb: "Breadcrumb",
    Button: "Button",
    Card: "Card",
    Checkbox: "Checkbox",
    CheckboxPanel: "Checkbox Panel",
    Chip: "Chip",
    Combobox: "Combobox",
    CookieConsent: "Cookie Consent",
    Countdown: "Countdown",
    DateInput: "Date Input",
    DescriptionList: "Description List",
    Expander: "Expander",
    Feedback: "Feedback",
    File: "File",
    FileInput: "File Input",
    Flex: "Flex",
    Help: "Help",
    Icon: "Icon",
    IconButton: "Icon Button",
    Image: "Image",
    InputGroup: "Input Group",
    InputPanel: "Input Panel",
    Link: "Link",
    LinkList: "Link List",
    List: "List",
    Loader: "Loader",
    Logo: "Logo",
    Menu: "Menu",
    Message: "Message",
    Modal: "Modal",
    NavLink: "Nav Link",
    NumberInput: "Number Input",
    Pagination: "Pagination",
    Popover: "Popover",
    ProgressBar: "Progress Bar",
    RadioButton: "Radio Button",
    RadioPanel: "Radio Panel",
    ScreenReaderOnly: "Screen Reader Only",
    Search: "Search",
    SegmentedControl: "Segmented Control",
    Select: "Select",
    SummaryTable: "Summary Table",
    SystemMessage: "System Message",
    Table: "Table",
    TableOfContents: "Table Of Contents",
    Tabs: "Tabs",
    Tag: "Tag",
    TextArea: "Text Area",
    TextInput: "Text Input",
    Toast: "Toast",
    ToggleSwitch: "Toggle Switch",
    Tooltip: "Tooltip",
    Typography: "Typography",
} as const;

export type ComponentName = keyof typeof COMPONENT_NAMES;
