import { figma } from "@figma/code-connect";
import { FileInput } from "./FileInput.js";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    FileInput,
    "https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv?node-id=13371%3A2526",
    {
        imports: [
            'import { FileInput } from "@fremtind/jokul/components/file-input";',
        ],
        props: {
            // These props were automatically mapped based on your linked code:
            description: figma.string("Prompt"),
            // No matching props could be found for these Figma properties:
            // "prompt": figma.string('Prompt'),
            // "hoverDrop": figma.boolean('Hover/Drop'),
            // "showLabel": figma.boolean('Show Label'),
            // "state": figma.enum('State', {
            //   "Default": "default",
            //   "File Uploaded": "file-uploaded",
            //   "Error": "error"
            // }),
            // "small": figma.boolean('Small')
        },
        example: (props) => (
            <FileInput
                value={[]}
                onChange={() => {}}
                legend="Last opp"
                description={props.description}
            />
        ),
    },
);
