import { figma } from "@figma/code-connect";
import { File } from "./File.js";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    File,
    "https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv?node-id=23716%3A13629",
    {
        imports: ['import { File } from "@fremtind/jokul/components/file";'],
        props: {
            // These props were automatically mapped based on your linked code:
            fileName: figma.string("Filename(size)"),
            state: figma.enum("State", {
                Error: "error",
                Loading: "loading",
            }),
            variant: figma.enum("Variant", {
                List: "list",
                Card: "card",
            }),
            // No matching props could be found for these Figma properties:
            // "filenamesize": figma.string('Filename(size)')
        },
        example: (props) => (
            <File
                fileName={props.fileName}
                fileType="jpg"
                fileSize={14_000}
                state={props.state}
                variant={props.variant}
            />
        ),
    },
);
