name: Pull request

on:
    pull_request:
        branches: ["main"]
    merge_group:
        types: [checks_requested]

run-name: Bygg og test ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}

env:
    PREFIX_PATHS: true

jobs:
    build:
        name: Sjekk for endringer og bygg pakker
        if: ${{ !contains(github.event.sender.login, 'fremtind-bot') }}
        outputs:
            jokul: ${{ steps.changes.outputs.jokul }}
            components: ${{ steps.changes.outputs.components }}
            stories: ${{ steps.changes.outputs.stories }}
            changeset: ${{ steps.changes.outputs.preview }}
            testlint: ${{ steps.changes.outputs.testlint }}
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Check for changes that require extra verification
              if: ${{ github.event_name != 'merge_group' }}
              uses: ./actions/paths-filter
              id: changes
              with:
                  filters: |
                      jokul:
                        - "**/packages/jokul/src/**/*.scss"
                        - "**/packages/jokul/src/**/!(*.stories|*.test|*.d).ts"
                        - "**/packages/jokul/src/**/!(*.stories|*.test).tsx"
                      components:
                        - "**/packages/jokul/src/components/**/*.scss"
                        - "**/packages/jokul/src/components/**/!(*.stories|*.test|*.d).ts"
                        - "**/packages/jokul/src/components/**/!(*.stories|*.test).tsx"
                      stories:
                        - ".storybook/**/*.(ts|tsx|scss|html)"
                        - ".storybook-public/**/*"
                        - "**/packages/jokul/src/components/**/*.stories.tsx"
                      changeset:
                        - ".changeset/!(README).md"
                      testlint:
                        - "**/*.js"
                        - "**/*.scss"
                        - "**/*.ts"
                        - "**/*.tsx"
                        - "**/vite.test.config.mjs"
                        - "pnpm-lock.yaml"

            - name: Remind about documentation
              if: (steps.changes.outputs.jokul == 'true' && steps.changes.outputs.changeset == 'false') || (steps.changes.outputs.components == 'true' && steps.changes.outputs.stories == 'false')
              uses: marocchino/sticky-pull-request-comment@da224cb0e3c8b27cae68d40c93649421b5b93e45
              with:
                  header: reminders
                  GITHUB_TOKEN: ${{ secrets.FREMTIND_BOT_ACCESS_TOKEN }}
                  message: |
                        Hei, @${{ github.event.sender.login }}! Takk for at du bidrar til Jøkul! 🙌
                        For å sørge for at endringene er godt dokumentert er det fint om du husker å gjøre disse tingene:
                        
                        - [ ] **Dokumenter endringer** 📝
                          Sørg for at du har dokumentert endringene i et [changeset](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) hvis de skal føre til en ny release av `@fremtind/jokul`.
                        ${{ steps.changes.outputs.components == 'true' && steps.changes.outputs.stories == 'false' &&  '- [ ] **Oppdater eller lag nye stories** 📚
                          Hvis du har endret eller lagt til ny funksjonalitet i komponenter må du huske å oppdatere eller legge til Storybook-stories for dette i komponenten(e).
                        - [ ] **Oppdater informasjon i Sanity** 📖
                          Hvis du har endret eller lagt til ny funksjonalitet i komponenter må du huske å oppdatere informasjonen om komponenten(e) i Sanity.' }}

            - name: Setup pnpm
              if: steps.changes.outputs.has_matches == 'true' || github.event_name == 'merge_group'
              uses: pnpm/action-setup@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              if: steps.changes.outputs.has_matches == 'true' || github.event_name == 'merge_group'
              with:
                  node-version: 22
                  cache: "pnpm"

            - name: Restore Monorepo Runner Cache
              if: github.event_name == 'merge_group'
              uses: actions/cache/restore@v3
              with:
                  path: .nx
                  key: nx-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
                  restore-keys: |
                      nx-${{ hashFiles('pnpm-lock.yaml') }}-

            - name: Cache Monorepo Runner
              if: github.event_name == 'pull_request' && steps.changes.outputs.has_matches == 'true'
              uses: actions/cache@v3
              with:
                  path: .nx
                  key: nx-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
                  restore-keys: |
                      nx-${{ hashFiles('pnpm-lock.yaml') }}-

            - name: Install dependencies
              if: steps.changes.outputs.has_matches == 'true' || github.event_name == 'merge_group'
              run: pnpm install

            - name: Build packages
              if: steps.changes.outputs.has_matches == 'true' || github.event_name == 'merge_group'
              run: pnpm build

    testlint:
        name: Kjør tester og linting
        needs: [build]
        if: github.event_name == 'merge_group' || (needs.build.outputs.testlint == 'true' && !contains(github.event.sender.login, 'fremtind-bot'))
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: "pnpm"

            - name: Restore Monorepo Runner Cache
              uses: actions/cache/restore@v3
              with:
                  path: .nx
                  key: nx-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
                  restore-keys: |
                      nx-${{ hashFiles('pnpm-lock.yaml') }}-

              # Steget må være med, men vil være cachet
            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: pnpm build

            - name: Lint and test
              run: pnpm ci:test

    preview:
        name: Publiser forhåndsvisning
        needs: [build]
        if: github.event_name != 'merge_group' && (needs.build.outputs.components == 'true' || needs.build.outputs.stories == 'true')
        runs-on: ubuntu-latest
        env:
            PREVIEW_PATH: preview/${{ github.event.pull_request.head.ref }}
        permissions:
            actions: write
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: "pnpm"

            - name: Restore Monorepo Runner Cache
              uses: actions/cache/restore@v3
              with:
                  path: .nx
                  key: nx-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
                  restore-keys: |
                      nx-${{ hashFiles('pnpm-lock.yaml') }}-

              # Steget må være med, men vil være cachet
            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: pnpm build

            - name: Add a comment with a link to the preview
              uses: marocchino/sticky-pull-request-comment@da224cb0e3c8b27cae68d40c93649421b5b93e45
              with:
                  header: preview
                  GITHUB_TOKEN: ${{ secrets.FREMTIND_BOT_ACCESS_TOKEN }}
                  message: |
                      <span aria-hidden="true">🔄</span> **Gjør klar en forhåndsvisning…**
                      <span aria-hidden="true">🔍</span> Commit: ${{ github.sha }}

            - name: Build site
              run: pnpm build-storybook

            - name: Deploy preview
              env:
                  GH_TOKEN: ${{ secrets.BOT_PUBLISH_TOKEN }}
              run: |
                  git config user.email "fremtind.designsystem@fremtind.no"
                  git config user.name "fremtind-bot"
                  git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/fremtind/jokul.git
                  pnpm gh-pages --add --dist storybook-static --dest ${{ env.PREVIEW_PATH }} --message "docs: preview #${{ github.event.number }}"

            - name: Add a comment with a link to the preview
              uses: marocchino/sticky-pull-request-comment@da224cb0e3c8b27cae68d40c93649421b5b93e45
              with:
                  header: preview
                  GITHUB_TOKEN: ${{ secrets.FREMTIND_BOT_ACCESS_TOKEN }}
                  message: |
                      <span aria-hidden="true">✅</span> Forhåndsvisning: https://jokul.fremtind.no/${{ env.PREVIEW_PATH }}/
                      <span aria-hidden="true">🔍</span> Commit: ${{ github.sha }}

                      Forhåndsvisningen blir tilgjengelig innen et par minutter. Den fjernes automatisk når pull requesten lukkes.