import { figma } from "@figma/code-connect";
import React from "react";
import { Loader } from "./Loader.js";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Loader,
    "https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv?node-id=5199%3A7304",
    {
        imports: [
            'import { Loader } from "@fremtind/jokul/components/loader";',
        ],
        props: {},
        example: () => (
            <Loader textDescription="Beskriv hvorfor du viser loaderen" />
        ),
    },
);
